numero1= float(input("Primer numero:" ))
numero2= float(input("Segundo numero:"))

print("Suma")
print(numero1, "+", numero2, "=", numero1 + numero2)
print("Resta")
print(numero1, "-", numero2, "=", numero1 - numero2)
print("Multiplicacion")
print(numero1, "*", numero2, "=", numero1 * numero2)
print("Division")
print(numero1, "/", numero2, "=", numero1 / numero2)
print("Modulo")
print(numero1, "%", numero2, "=", numero1 % numero2)
print("Exponente")
print(numero1, "**", numero2, "=", numero1 ** numero2)