presupuesto_total = float(input("Presupuesto total del evento:"))
costo_venue = float(input("Costo del venue:"))

print("Suma")
print(presupuesto_total, "+", costo_venue, "=", presupuesto_total + costo_venue)
print("Resta")
print(presupuesto_total, "-", costo_venue, "=", presupuesto_total - costo_venue)
print("Multiplicacion")
print(presupuesto_total, "*", costo_venue, "=", presupuesto_total * costo_venue)
print("Division")
print(presupuesto_total, "/", costo_venue, "=", presupuesto_total / costo_venue)
print("Modulo")
print(presupuesto_total, "%", costo_venue, "=", presupuesto_total % costo_venue)
print("Exponente")
print(presupuesto_total, "**", costo_venue, "=", presupuesto_total ** costo_venue)
